# .github/workflows/reveal-secrets.yml
name: Reveal Secrets
on:
  workflow_dispatch:

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Print encoded
        run: |
          echo "${{ secrets.INSTAGRAM_USER_ID }}" | base64
          echo "${{ secrets.META_ACCESS_TOKEN }}" | base64
